"""add provider fields to saved jobs

Revision ID: 5707b41631ee
Revises: 69372bce7048
Create Date: 2026-07-20 00:29:31.879902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5707b41631ee'
down_revision = '69372bce7048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('meeting_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_job_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company_logo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('job_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_saved_job_user_source_external_id', ['user_id', 'source', 'external_job_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_saved_job_user_source_external_id', type_='unique')
        batch_op.alter_column('job_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('published_at')
        batch_op.drop_column('description')
        batch_op.drop_column('salary')
        batch_op.drop_column('job_type')
        batch_op.drop_column('category')
        batch_op.drop_column('company_logo')
        batch_op.drop_column('external_job_id')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.alter_column('meeting_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
