"""Add password hash to users

Revision ID: 69372bce7048
Revises: 9509c4b7bf4f
Create Date: 2026-07-18 19:43:34.382263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69372bce7048'
down_revision = '9509c4b7bf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
